### ISSUE TITLE
Optimization: Save Query Statements in Separate File to Avoid Recalculation During Program Execution

### ISSUE THREAD

**Issue by mylinhdao** [MaibornWolff/metric-gardener#113]
**Let's discuss a new approach to enhance the performance:**
The computation of query statements occurs each time the program is run, resulting in unnecessary resource consumption. Notably, the result remains constant unless changes are made to 'nodeTypeConfig.json.' To optimize this process, consider relocating the logic to 'import-grammars' and storing the query statements in a file. This adjustment would reduce recalculations, thereby enhancing overall efficiency.

**Comment by ResistantBear** [comment]
According to the performance analysis from #144, the impact of compiling these query strings out of our nodeTypesConfig.json is not expected to have a significant impact on the overall runtime of the program. I therefore suggest to not prioritize this optimization.

We should also keep in mind that when storing these query string, we have to make sure to regenerate them after we do any change to our nodeTypesConfig.json and if we do any change on how we compile the query string for one particular metric. So this optimization would have some disadvantages when it comes to maintenance.

**Comment by ce-bo** [comment]
I appreciate your idea. However, this is not planned to be implemented due to the reason that I do not expect a user to parse a code base many times.
