### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/metric-gardener#14]
Columns: New Issues, Backlog, In Progress, Further Inquiry, Review, Closed

**Comment by ResistantBear** [comment]
GitHub has an internal mechanism for this called "Project Boards" found under the "Projects" tab of a repository.
However, I do not seem to have the appropriate rights to create a new Project Board for this repository.
[https://docs.github.com/en/github-ae@latest/issues/organizing-your-work-with-project-boards/managing-project-boards/creating-a-project-board#creating-a-repository-project-board](How to create a repository project board)

**Comment by BridgeAR** [comment]
If we pull metric-gardener into the CodeCharta monorepo, let's maybe combine the kanban board? Or would you rather keep these separated?

**Comment by ResistantBear** [comment]
We had discussed that idea in the last weekly. We probably keep them as separated repositories.
