### ISSUE TITLE
Setup Renovate

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/metric-gardener#15]
Integrate Renovate for automated dependency updates like it is used in CodeCharta repo.

**Comment by michaelalper-cezik-mw** [comment]
Renovate has successfully been set up in the metric-gardener repository.

**Important note:**
Each time tree-sitter grammar is updated it is necessary to manually run the import-script. More information on how to run the script can be found here: https://github.com/MaibornWolff/metric-gardener/blob/main/UPDATE_GRAMMARS.md

**Comment by ResistantBear** [comment]
We probably close this issue once we verified that the weekend-schedule and grouping has worked as expected.

**Comment by ce-bo** [comment]
@ResistantBear does it work and can this issue be closed?

**Comment by ResistantBear** [comment]
Jep. Here and there, there occur some minor issues with the dependencies for which we have to re-group the dependency updates, but we have opened new issues for these.

**Comment by ResistantBear** [comment]
Jep. Here and there, there occur some minor issues with the dependencies for which we have to re-group the dependency updates, but we have opened new issues for these.
