### ISSUE TITLE
Option to parse only specific programming languages

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/metric-gardener#178]
As a User I want to configure which programming languages are going to be parsed, so that I can avoid unnecessary parsing and outputs.

**Comment by BridgeAR** [comment]
Is this really necessary in case the parsing is fast enough? We already compress the output file on CC side, so that's not an issue either (the overall size is mostly really low that way).

**Comment by ce-bo** [comment]
I had the same thoughts. It was a feature request from a colleague, so I decided to track it here. It is not yet in our backlog but needs further thoughts.
