### ISSUE TITLE
Lines of code not always correct

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#18]
I have tested a C++ source code file with 739 lines of code. However, the json produced by metric gardener states that the file has 0 lines_of_code and 0 real_lines_of_code, which is just not correct.

**Comment by ResistantBear** [comment]
Ok, the root cause for this issue seems to be that for some files, the root node of the tree returned by the parser of Tree-sitter is "ERROR" instead of "translation_unit", which is probably a bug of the C++ parser of Tree-sitter. 

However, I wonder if it is necessary to check if there is such a node? Are there cases where this procudure solves an issue? Otherwise, I would suggest to remove this procedure in favor of returning `tree.rootNode.endPosition.row` as the lines of code, which is robust in the case of an deviant root node. It should improve performance, as it does not need to perform any queries, too.

**Comment by ce-bo** [comment]
Is there no translation unit expression in the grammar anymore?

I like your suggestion to just use tree.rootNode.endPosition.row instead. Do you know how the LOC metric is implemented in metric-gardener? Is it just the number of lines in a file or is it the number of lines minus e.g. empty or comment lines?

The Definition of LOC in metric gardener should be explained somewhere. Would you take care please?

**Comment by ResistantBear** [comment]
I already asked myself if there is a concrete definition of the available metrics somewhere, as I know that one can define "lines of code" in many different ways... I assume there is no such definition documented currently? 
As far as I can say, the current code just returns the overall number of lines for LOC, while there is the separate "Real LOC" metric for ignoring comments and empty lines.

There is still a translation_unit expression and the current procedure seems to work fine for most files. However, as mentioned, for some files, Tree-sitter generates an "ERROR" node instead, which is probably, well, an error 😄

**Comment by ce-bo** [comment]
I think there is no description of metrics yet. You might want to add it to the Readme?
