### ISSUE TITLE
Switch to the built-in Node.js test runner or other test runner

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#20]
@BridgeAR suggests to switch to the built-in Node.js test runner or mocha.

Jest is slow and does pretty bad things internally that features are not working as expected (e.g., `instanceof` being broken, it manipulates assertion libraries output and handling and more).

_Originally posted by @BridgeAR in https://github.com/MaibornWolff/metric-gardener/pull/17#discussion_r1437577529_

**Comment by ResistantBear** [comment]
We have to replace the following functionalities that we currently use via jest and that do not seem to be natively supported either the node.js test runner nor mocha. Any replacement has to work with TypeScript, obviously.

- [ ] Snapshot tests
- [ ] Test coverage

**Comment by clemens-mw** [comment]
https://2022.stateofjs.com/en-US/libraries/testing/
Retention Ranking:
1. Vitetst
2. Testing Library
3. Playwright
4. Jest
5. Storybook
6. Cypress
7. Puppeteer
8. Mocha
9. AVA
10. Jasmine
11. WebrdirverIO
12. TestCafe
13. Selenium

Other Frameworks:
- Karma
- Nightwatch

Other Tools:
- Chai (assertions)
- Sinon (stubs, spies, mocks, fake timers)

**Comment by clemens-mw** [comment]
## Vitest

- Mocking: YES
- Coverage: YES
- Snapshots: YES

### Advantages

- Very easy migration from Jest (very few changes needed)
- Can use forks pool (to resolve issue #65)

### Drawbacks

- None?

### Tests

I ran all current tests. Performance is better than Jest.
Using the default threads pool has the same issue as Jest (#65). Using the forks pool solves the issue.
`MetricCalculator.test.ts` fails. I will have a look at it tomorrow.
