### ISSUE TITLE
Discussion TS/TSX: which type alias should be counted for "classes" metric

### ISSUE THREAD

**Issue by mylinhdao** [MaibornWolff/metric-gardener#213]
There are many ways to write a type alias in TS/TSX see this [cheat sheet](https://www.typescriptlang.org/static/TypeScript%20Types-ae199d69aeecf7d4a2704a528d0fd3f9.png) .
We should clarify which of them should be counted for "classes" metric, especially these kind of type aliases:
```
type union = {a: 1} & {b: 2};
type intersect = {a: 1} | {b: 2}; // object
type tuple = [name: string, age: number];
```
The result of this discussion must be applied to PR #199

**Comment by ChristianHuehn** [comment]
I propose that we leave those out of classes metrics for now. But will come up with an idea on how to count parts of them as interfaces for class metrics
