### ISSUE TITLE
Updating tree sitter grammars

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#24]
Requested by @BridgeAR in https://github.com/MaibornWolff/metric-gardener/pull/17#pullrequestreview-1798071997

As there seem to be some issues with the existing mappings, too, these should be sorted out, too. There is, for example, only PHP as applicable language for all binary expression operators, or nodes marked as statements which are no statements, see https://github.com/MaibornWolff/metric-gardener/issues/30#issuecomment-1880841893

**Comment by ce-bo** [comment]
Let's get rid of the current import script and introduce a new one that allows to update an already supported language and its already mapped expression easily.

**Comment by ResistantBear** [comment]
Notes for further work:
- [ ] Binary_Expression gets removed in python, seems to use the syntax node boolean_operator instead. So special handling for binary_expression needs to be adjusted to also include this node. May change the code for the special handling to handle such cases more elegantly.
- [ ] Coupling test cases seem to be affected by updating the node mappings. That needs to be investigated.
