### ISSUE TITLE
Make @types/node version equal to specified minimum engine version 

### ISSUE THREAD

**Issue by clemens-mw** [MaibornWolff/metric-gardener#257]
@types/node version should match specified engine in package.json?
or can @types/node version be higher?
should we ignore renovate pull requests like #157?

**Comment by ResistantBear** [comment]
As far as I have understand, the major version of `@types/node` corresponds to the version of node.js, and as package.json specifies the minimum version of node.js we currently want to support, yes, it should match that then.

Yes, you can continue to ignore it probably, until we some day want/have to increase the required node.js version.
