### ISSUE TITLE
Remove seemingly unused dependencies

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#27]
As pointed out by @BridgeAR in https://github.com/MaibornWolff/metric-gardener/pull/17#discussion_r1437657456, there seem to be unused dependencies that could be removed. To be verified by @ce-bo.

**Comment by ce-bo** [comment]
Please check by yourself if this library is not in use anymore. I don't remember the use case for this one at all. So, yes maybe we can just remove it.
