### ISSUE TITLE
import-grammars should format output using prettier

### ISSUE THREAD

**Issue by clemens-mw** [MaibornWolff/metric-gardener#305]
one option could be:
`exec("npx prettier ./src/parser/config/nodeTypesConfig.json --write");`
or use the API:
https://prettier.io/docs/en/api.html

- [ ] move prettier from devDependencies to dependencies

**Comment by clemens-mw** [comment]
I just thought about making `import-grammars` a npm run script instead of including this into the CLI of the parser?

**Comment by ChristianHuehn** [comment]
The idea in general is nice. But I would argue that the output doesn't have to be human readable.  Most IDEs and Editors support this out of the box. I would rate this below low priority therefor I close it.
