### ISSUE TITLE
Comment blocks in python are not handled

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#31]
Comment blocks in python like
"""
comment line here
"""
are not handled. 

This is because such comments get parsed as (expression_statement (string)) instead of (comment). As that seems to be an issue with the tree-sitter parser for python, I do not recommend to fix this here, as that would necessitate a workaround especially for that language.

**Comment by BridgeAR** [comment]
This is a tricky one. Python handles multi-line comments different than other programming languages. They are just "regular" expressions.
How to interpret them correct is a difficult decision and I guess that won't be "fixed". As such, having a special handling in our code might be required to parse those. Alternative print a warning when parsing python with the concrete metric.

**Comment by BridgeAR** [comment]
You might want to open an issue in the python library to ask if they would be interested in trying to differentiate the two or not.

**Comment by ResistantBear** [comment]
> This is a tricky one. Python handles multi-line comments different than other programming languages. They are just "regular" expressions. How to interpret them correct is a difficult decision and I guess that won't be "fixed". As such, having a special handling in our code might be required to parse those. Alternative print a warning when parsing python with the concrete metric.

Ok, mh. Interesting. If they are indeed handled as normal expressions, the behaviour of classifying them as "expression_statement" should be correct then from a syntactic view, I guess. That would also arise the question, wheter or not to count them as "comment line" at all. If there is no strong opinion to count them into the comment lines metric, we might leave it as it is.

**Comment by ResistantBear** [comment]
Such "afterMetricHooks" would also have to be specific for each metric. But otherwise, something similar should work, I guess. It might also happen that we need to override the general logic for some language one day because it is not sufficient to just add some other value to the result, or because the logic does not apply at all. On the other hand, if the general logic is ok and we only need to add to that result, like it is the case here, this solution could avoid redundancy. On the other hand, we could call the function with the general logic again from the overriding function to avoid that redundancy. Mh.

**Comment by ResistantBear** [comment]
However, the main issue here would be that part of identifying these multi-line strings and determining that they are not passed to anything. I currently have a look at the dependency analysis code to fix an issue that occurs at identifying passed parameters, etc., when updating the grammars. There is a lot that can go wrong there when the grammar changes, also to keep up with all variants that the grammar allows for on such a position, so this is not going to be trivial and the maintenance of handling this could become an issue. But there is probably no way around it.

**Comment by ResistantBear** [comment]
Ok, it might be simpler as expected, as it seems like the Python tree sitter grammar always puts such solitude strings into a single `(expression_statement)` while for other kinds of operations with these strings, there is another node type surrounding the string node, e.g. `call`
