### ISSUE TITLE
Node version problem: `npm test` does not work

### ISSUE THREAD

**Issue by mylinhdao** [MaibornWolff/metric-gardener#323]
In `package.json`, we have defined the required node version to `"node": ">=18"`. But actually, `npm run test` seems to only works on Node v20 (tested on v20.11.0). If I run it on Node v18.20.2, the tests could not be found. 
I could not find out why. So any answers and helps are very appreciated!

**Comment by clemens-mw** [comment]
TLDR: run `npm rebuild`

If you used v20 before and installed the dependencies, the [`install` script of `tree-sitter`](https://github.com/tree-sitter/node-tree-sitter/blob/master/package.json#L54) will build the node bindings using v20. If you switch to v18 afterwards you will receive the error `The module was compiled against a different Node.js version`. You can fix this by running `npm rebuild`, `npm install` or `npm ci` locally to build the dependencies again.

**Comment by mylinhdao** [comment]
@clemens-mw thank you very much for answering :) It works with `npm rebuild` and `npm ci` !
