### ISSUE TITLE
May improve reliability of async operations

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#39]
Is the following issue resolved for the asynchronous code handling the await of multiple promises in GenericParser and MetricCalculator? (see answers in the linked original pull request #23) 
If yes, this issue should be closed.

"The issue is, that this is a frequent pattern for an incomplete promise chain. Therefore, Node.js decided to track these promises to provide users a hint that they did not handle the promise properly. Node.js just can't know what is going to happen in the future and rather fails early."

_Originally posted by @BridgeAR in https://github.com/MaibornWolff/metric-gardener/pull/23#discussion_r1453521567_

**Comment by ce-bo** [comment]
Since this is marked as further inquiry, would you add the open questions?

**Comment by ce-bo** [comment]
@BridgeAR could you please give an advice on how to improve the promise chain handling? Thank you.

**Comment by ResistantBear** [comment]
We finally clearified the possible pitfalls when working with lists of promises in Node.js with @BridgeAR.
Our current proposal in https://github.com/MaibornWolff/metric-gardener/pull/217 should be fine accordingly.
