### ISSUE TITLE
Add tests for file metrics for Java 

### ISSUE THREAD

**Issue by mylinhdao** [MaibornWolff/metric-gardener#40]
- Test the metrics returned by calculateMetrics(...) in GenericParser for every metrics (lines_of_code, real_lines_of_code, commentLines, classes, functions, mcc)

**Comment by ce-bo** [comment]
Since this is blocked an marked as further inquiry, are there any open questions? Why is it blocked? Would you please shortly add a comment, so that it is clear for everyone? Thank you :-)

**Comment by ResistantBear** [comment]
Blocked because of #41  
There are no test cases for MCC yet and MCC is not really defined currently.
If #41 takes longer, we could add test cases that adhere to the MCC as defined by the source code (Branch instructions + boolean operators = MCC) and move ahead with this, however.
