### ISSUE TITLE
Add automated test cases for --import-grammars

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#55]
Now that #53 is closed and manual comparison of the nodeTypes.json-output is possible, it would be nice to have a repeatable automated test for this as well. 

One idea would be to add a test that uses fixed versions of nodeTypesConfig.json and fixed versions of the grammar's node-types.json as input and compare the result to yet another fixed reference version of nodeTypesConfig.json and nodeTypesChanges.csv to ensure that the whole script works properly. But adding unit tests for the single functions can be also considered.

**Comment by clemens-mw** [comment]
relates to #228
