### ISSUE TITLE
Real lines of code fails with new grammar for java when using multi-line string literals

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#58]
Code like the following does fail with the new Java grammar:

```Java
String multiLine = """
    Multi
    Line
   String
""";
```

**Comment by ce-bo** [comment]
Let's mark this as a bug and move it to the backlog. I think this has a high priority. Would a downgrade to the old grammar makes sense?

**Comment by ce-bo** [comment]
Would you please provide the error message/description? I am not sure what is failing exactly.
