### ISSUE TITLE
Exclude node types that have subtypes in the import script

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#61]
There was an issue with the updates Java-grammar, that the "comment" node type has now two new subtypes for "line_comment" and "block_comment" (see #56). Running a query for the "comment" node type resulted in a tree-sitter query exception. 
For now, the "comment" node type was manually deactivated for Java by using the "activated_for_languages"-field. However, if such "super node types" which have subtypes are generally something like an "abstract node type" which cannot be queried - and it looks like that is the case - the import script should not include these node types into the nodeTypesConfig.json (for that language), but only the subtypes.

**Comment by BridgeAR** [comment]
Could we just feature detect each node we use and adjust our queries accordingly?

That way it's fast and yet we are able to query everything without having to manually work with the `activated_for_languages` field.

**Comment by ResistantBear** [comment]
It could already cause bugs in languages for which we have no test cases and is very likely to cause them when updating the grammars again, but yeah, it do not causes known bugs other than the one I fixed via the manual, temporary workaround. 

I nevertheless think this change is both important in the long run and would only require a very minor change in the import script to fix, while other people that might stumble upon it in the future might not know where the issue lies.

**Comment by ResistantBear** [comment]
The section about "Supertype Nodes" in the tree-sitter documentation does indeed confirm that such types are abstract https://tree-sitter.github.io/tree-sitter/using-parsers

**Comment by ResistantBear** [comment]
> Could we just feature detect each node we use and adjust our queries accordingly?
> 
> That way it's fast and yet we are able to query everything without having to manually work with the `activated_for_languages` field.

Unfortunately, I do not understand what you mean with "feature detect"...
