### ISSUE TITLE
Do not count for default cases in Java, Python, Kotlin and C++ switch case blocks

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#64]
Currently, the code does not differentiate between case and default labels in a switch case statement in Java, while it does do so for C#. This is caused by the grammar for java using the same node_type for both labels.
Probably needs a special treatment in our code.

Once this is implemented, un-skip the test case for java switch case statements inside `JavaMetric.test.ts`.

**Comment by ce-bo** [comment]
Thank you @ResistantBear. We should open a feature request for the java grammar to separate case and default labels in a switch statement.
For now it would be a pragmatic solution to just let it as it is which means to also count the default label even if this is not correct. It most probably does not falsify the results in a crucial way.

A language specific handling could be implemented, if there is no response from the dev-team of tree-sitter-java grammar after some time. I added priority medium for this, because there are other more important tasks for now anyway.

**Comment by ResistantBear** [comment]
We have opened https://github.com/tree-sitter/tree-sitter-java/issues/171 to request this differentiation.

**Comment by michaelalper-cezik-mw** [comment]
Same problem for Python, probably because default keyword is not used there. Instead, it is just another case with a underscore as wildcard like this:
`case _:`

Can be identified by a case_pattern node without any child nodes.

**Comment by michaelalper-cezik-mw** [comment]
Same behaviour for Kotlin where the default branch is specified by `else -> ...`

The node type given by tree-sitter is the same as for the non-default branches (when_entry) but it can be identified by a missing when_condition child node.

**Comment by ResistantBear** [comment]
Mh, that seems to get a common problem for most grammars, that they do not differentiate between case and default labels in try-catch-blocks, unlike C#. How unfortunate. 

The easiest solution would be to also count default-labels, then. That could be done by just changing the config-file. On the other hand, doing so would be not in line with the definition of the Cyclomatic Complexity as it does not lead to a new edge in the control flow, just like an else-statement, which we do not count either.

Having special treatments for various languages, or making the definition/calculation of that metric inconsistent. That's a difficult one.

**Comment by ResistantBear** [comment]
I noticed that there is a test missing for switch-case-statements in C++. 
Unfortunately, the tree-sitter grammar for that language suffers from the same issue.

**Comment by ResistantBear** [comment]
> Let's activate this test and asume that default labels are counted as well.
We agreed that it is ok for now to also count them. So let's relfect that in the tests but we should mention that in the metric definitions.

_Originally posted by @ce-bo in https://github.com/MaibornWolff/metric-gardener/pull/101#discussion_r1485851071_

**Comment by ResistantBear** [comment]
So we for now accept that we have a deviation between how different languages handle this. 

Our feature request for Java to add a distinction like the C# grammar does has been declined. To further proceed on this issue, I would suggest to take a look into how simple/hard it would be to come up with a special handling for switch labels here that works for (almost) all languages. Maybe checking the number of child nodes of a "switch_label" and 1-2 more options in a generic way is sufficient for most languages.
