### ISSUE TITLE
Race condition when running all tests files

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#65]
We have encountered an issue where some tests "just fail" because of tree.rootNode being undefined when running all tests, e.g. via "npm test". This seems to be triggered by the higher number of test files or test cases in this PR, but also happened seldomly before. 

As it turns out, this is probably caused by a race condition in the tree-sitter library.
See https://github.com/tree-sitter/node-tree-sitter/issues/181
There is a potential fix for this linked, but it never got merged:
https://github.com/tree-sitter/node-tree-sitter/pull/75

_Originally posted by @ResistantBear in https://github.com/MaibornWolff/metric-gardener/issues/42#issuecomment-1918743774_

**Comment by ResistantBear** [comment]
Unfortunately, this error occurs quite often for me currently. Could be that #92 made things worse instead of better for this issue. Difficult to say with race conditions.

**Comment by ce-bo** [comment]
Could be fixed by https://github.com/tree-sitter/node-tree-sitter/pull/75

**Comment by ResistantBear** [comment]
It's already linked in the top description of this issue. However, taking a look on it again, that PR has been closed now without merge. 

https://github.com/tree-sitter/node-tree-sitter/pull/190#discussion_r1502694496

Looking at the PR that is linked there as it mentioned PR 75, the project seems to be in favour of blaming jest for this issue and linked https://github.com/jestjs/jest/issues/9206 for this. They seem to have agreed on not supporting jest at all for that reason. 

So we might solve this issue via #20 ... as that would mean to change all test cases an find an alternative or add additional libraries for replacing our current snapshot tests as such tests are not natively supported by node or mocha, it would be nice to verify that that would indeed solve the problem.
