### ISSUE TITLE
C-style comment blocks are not always counted correctly

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#67]
The current implementation fails to handle block comments spanning over multiple lines if it starts in a line that is also touched by another comment. Example:

```ts
/**
 * This is a comment.
 */ let x = 5; /**
 *
 * This is also a comment.
 */
```

**Comment by ce-bo** [comment]
@ResistantBear  Does it fail or is it not counted properly?

**Comment by ResistantBear** [comment]
It is not counted properly. I have noticed that mistake while looking into the issue #31
