### ISSUE TITLE
Discuss whether to split test files into folders for each metric

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#75]
> Let's discuss with the team if we want to stick to dedicated folders with examples files for a single metric like /c-sharp/complexity/if-statements.cs.

_Originally posted by @ce-bo in https://github.com/MaibornWolff/metric-gardener/pull/69#discussion_r1477780405_

**Comment by ResistantBear** [comment]
See for futher discussion also https://github.com/MaibornWolff/metric-gardener/pull/66#discussion_r1477776474

**Comment by ce-bo** [comment]
@ResistantBear @michaelalper-cezik-mw @mylinhdao would you please discuss it, so that we can take a decision here? Thank you.

**Comment by michaelalper-cezik-mw** [comment]
In my opinion it would probably look cleaner and more structured so I would say we should do it :)

**Comment by ResistantBear** [comment]
I am against this proposal. It would mean to always only test a single kind of metric for a given test source file, which does not make any sense for longer/more complex files where it can be helpful to have test cases to check the results for different kinds of metrics for that file. We currently have a file "<language>-example-code.<file-extension> for most languages that plays this role. 
There is also no reason to have duplicates of edge case files like "empty file" or "one line" for multiple metrics (one for rloc, one for loc, one for commentlines, ...). The same applies for thinks like "counting function definitions" which is also part of the definition of two metrics, etc., this would also require two separate "files with function definitions".

I am also not sure if the current test approach of testing a single metric on a single file in most cases is the best approach, we could also discuss to check all metrics being calculated correctly for a given file (or test a given metric on all available files, not just some cherry-picked ones).

**Comment by ResistantBear** [comment]
I also do not agree that this would improve clarity, as we might get a shorter list of files to search for in a particular folder for a metric, but on the other hand, get many duplicate or very similar files, as there is also no inherent link between "metric" and "test source file", as discussed before.

**Comment by ResistantBear** [comment]
Obviously, creating similar files and checking them via some sort of compiler again does increase the work needed for writing new test cases, while finding already checked files to be reused by duplicating them is hindered by the larger number of overall files and the folder strucuture. We also would have to do this duplication for all existing test cases where there are test source files used that are also used for testing another kind of metric.

A benefit would be that we do not have to check which test cases are using a particular test source file if we change it, but the amount of work required for this is quite low and we probably do/should not update these source code example files that often/at all.
