### ISSUE TITLE
May refactor test cases to run the parser only once per .test.ts file

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#76]
Thinking of it, we may restructure the test cases inside one .test.ts file to make metric-gardener run once on all test files for that language and then let the test cases run assertions on these results. That should speedup the tests runs and dramatically reduce the probability of the race condition to occur 🤔

_Adopted from a post by @ResistantBear in https://github.com/MaibornWolff/metric-gardener/pull/66#discussion_r1477792077_

**Comment by ResistantBear** [comment]
May further mitigates #65

**Comment by ce-bo** [comment]
Are the tests too slow at the moment?

**Comment by ResistantBear** [comment]
Not necessarily. But this is a very easy to implement optimization and should drastically reduce the probablility of that race condition, too. I test it out for the C++ tests currently.

**Comment by ce-bo** [comment]
Alright, let's implement it if it helps us :-)
