### ISSUE TITLE
Stabilize supported programming languages by adding automated tests

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/metric-gardener#8]
ACs:
- Tests are added for programming languages that are flagged as unstable

Add tests for:

- [x] Java
- [x] C#
- [x] Python
- [x] C++
- [x] JavaScript
- [x] Kotlin

**Comment by ResistantBear** [comment]
Splitted out issue #40 to add test cases for Java

**Comment by ResistantBear** [comment]
Splitted out issue #44 for adding test cases for C#

**Comment by ResistantBear** [comment]
Splitted out issue #84 for adding test cases for C++

**Comment by michaelalper-cezik-mw** [comment]
Splitted out issue #87 for adding test cases for Python

**Comment by michaelalper-cezik-mw** [comment]
Splitted out issue #96 for adding test cases for Kotlin

**Comment by michaelalper-cezik-mw** [comment]
Splitted out issue #106 for adding test cases for JavaScript

**Comment by ResistantBear** [comment]
Closed as the issues #40, #44, #84, #84, #87, #96 and #106 that this issue comrpises have been closed.
