### ISSUE TITLE
Support parsing TSX code

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/metric-gardener#9]
As described [here](https://github.com/tree-sitter/tree-sitter-typescript) tsx is a different dialect than typescript.
Therefore we need to support both grammars.

**Comment by ResistantBear** [comment]
According to the flow documentation [linked here](https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow), flow-files can be differentiated from plain JavaScript-files via an annotiation in a file header comment. Currently, we solely identify the language of a file based on its file extension. 

One idea would be to parse the file in JavaScript and change the language and reparse the file if the first comment node includes a "@flow" string.

**Comment by ResistantBear** [comment]
Ok, TSX also seems to be a TypeScript-variant with embedded XML ([see here](https://www.typescriptlang.org/docs/handbook/jsx.html)). So that TSX-Grammar supports both Flow-annotated and .tsx-files then, I guess.

**Comment by ce-bo** [comment]
Please do not close this before TSX is supported with a stable set of metrics.
