### ISSUE TITLE
Discuss how to handle function declarations/interfaces without in-place implementation

### ISSUE THREAD

**Issue by ResistantBear** [MaibornWolff/metric-gardener#98]
Functions without implementations counts as function definitions for Java.
For C++, we (still) do not count function declarations without actual implementation at that place as a function currently and it definitely makes sense there. So it would again be a deviation between the metric result between different programming languages to count such pure function declarations/interfaces here. But there does not seem to be a way to change this behaviour for Java with the config file only, again :(

_Originally posted by @ResistantBear in https://github.com/MaibornWolff/metric-gardener/pull/94#discussion_r1484239470_

**Comment by ResistantBear** [comment]
> I think it is fine to caluclate this since it is a valid declaration. I would want to know as e.g. an Auditor if there are interfaces with a lot of methods declared.

_Originally posted by @ce-bo in https://github.com/MaibornWolff/metric-gardener/pull/94#discussion_r1484244698_

**Comment by ResistantBear** [comment]
I guess that we should count function declarations within C++ header files, then?

**Comment by ResistantBear** [comment]
> I think, yes. Or is there some reason against it? I am not a C++ professional but I would like to find header files with a lot or too much function declarations. That might would indicate a quality issue in such a file.

It should be fine when talking about the metric per file. 

It may almost double the number of overall functions, as with C++, we have to declare a function in a header if we want to use it outside of a file and should implement it outside of the header. At least for non-template functions, as they are usually implemented in the header itself, so the overall value would increase by 1 for a (usually more complex) template function compared to a "normal" function.

But as far as I know, we do not care about the sum of the metric values over all files, so it should be fine, yes.

**Comment by ce-bo** [comment]
@ResistantBear Do we want to close this discussion issue and create an actual feature request instead?

**Comment by ResistantBear** [comment]
I opened issue #146 for implementing this.
